### ISSUE TITLE
Increase Hexval 

### ISSUE THREAD

**Issue by ghost** [FastFilter/FilterPassword#8]
Hi,
Thanks for your good tools.
How can i increase Hexval to 32 hexadecimal characters filters?

Thanks.

**Comment by thomasmueller** [comment]
The short answer is you don't need to; 16 hexadecimal characters are enough. Just truncate the 32 characters to 16 characters.

The long answer is that 16 hexadecimal character is 64 bit, which allows for a lot of entries, without affecting the false positive probability in any significant way (see also https://en.wikipedia.org/wiki/Birthday_problem). Switching to 32 hexadecimal character would mean 128 bit, which is more than a UUID - that is not necessary.

**Comment by ghost** [comment]
Thanks for your answer.
Actually, my data 40 hex characters per line, it's mean truncate 8 characters to 32 characters. in the near future will add more some trillions. That why i need 32 characters for safe.

**Comment by lemire** [comment]
Your application may need long hashes, but from the point of you of a probabilistic filter, it does not much matter if you have good-quality hashes.

Prior to the query... Put all the starting 16-char hex characters from your hash values in the filter. Then at query time...

1. Ask the system, 'is this 40-hex hash value an element in my set?'
2. Pick the first 16 hex characters, ask the filter, 'is there an element in my set that starts with these 16 hex characters?'
3. If the answer is negative, then you know that the 40-hex hash is not in the set. End of request.
4. If the answer is positive, then there might be a match and you need to investigate more carefully (you may then need to do a more expensive query over the actual dataset).

The story is the same if you replace 40 by 400 or 1000000. You can still filter on the first 16 hashes.

Now, if you have a very, very large database with a number of entries that is close to 2^64, then the model starts to fall apart... and you may need a custom solution. But be mindful that 2^64 is a very large number.

**Comment by ghost** [comment]
> Your application may need long hashes, but from the point of you of a probabilistic filter, it does not much matter if you have good-quality hashes.
> 
> Prior to the query... Put all the starting 16-char hex characters from your hash values in the filter. Then at query time...
> 
> 1. Ask the system, 'is this 40-hex hash value an element in my set?'
> 2. Pick the first 16 hex characters, ask the filter, 'is there an element in my set that starts with these 16 hex characters?'
> 3. If the answer is negative, then you know that the 40-hex hash is not in the set. End of request.
> 4. If the answer is positive, then there might be a match and you need to investigate more carefully (you may then need to do a more expensive query over the actual dataset).
> 
> The story is the same if you replace 40 by 400 or 1000000. You can still filter on the first 16 hashes.
> 
> Now, if you have a very, very large database with a number of entries that is close to 2^64, then the model starts to fall apart... and you may need a custom solution. But be mindful that 2^64 is a very large number.

Thanks for your good information.
By the way how come i can search mode by list file by .txt? that is good search for multiple. speed hamper much or not i want to test with this. 
Pretend my database with a number of entries that is close to 2^64, so what a custom solution for this case?

**Comment by lemire** [comment]
> Pretend my database with a number of entries that is close to 2^64, so what a custom solution for this case?

It is not a scenario that is supported by the software in this project. It would require more engineering. If you'd like to work on it and contribute to the project, that would be great.

I am going to close this issue.
