### ISSUE TITLE
related project

### ISSUE THREAD

**Issue by oschonrock** [FastFilter/FilterPassword#9]
Making you aware of a related project I have recently published:

https://github.com/oschonrock/hibp

Similar application on HIBP pw db, with different priorities on resources and data pipeline:

- HIBP database is in not available in whole file downloads anymore (for 3+yrs already), and definitely not as "sorted by count desc". Official downloader is very slow, takes 1hr even on 1Gb/s network. Record count is also up, at nearly 1billion now. Text file size is 38GB. Therefore my project includes a high performance downloader which can save as text or a binary format (about half the size of txt). Utilities exist for "top N by count" slicing, "external disksort", and converting to/from binary, diff, etc. 

- My project is not a "probabilistic filter", it gives exact answers with "leak-count" of actual records by traditional techniques.. ie binary search on sorted binary data.  This results in a different resource usage profile. CPU and memory usage during download and query are very low. Max 100MB during download (can  be tuned down), and <10MB during querying. There is no "build" the data's "sorted by hash order" is maintained from download, converted to binary and written to disk. No significant amount of memory is required. 

- However, my project uses 21GB of disk space (on 1billion records, not 500million) for a complete database with deterministic, exact answers. It takes just 6 mins to download (1Gbit/s connection) and is instantly ready to run. This can be reduced with TopN etc.

- Query performance on my project is actual in a similar ballpark to your. 1k req/s to 12kreq/s depending on hardware and usage of --`toc`. This probably exceeds most needs. 

- There is a "table of contents" feature which pre-indexes the binary db (about 1min < 5MBmemory) which does a bitmask match of the queried hash to restrict the binary search to a range and this reduce disk accesses by 2/3rds by default. 

- NTLM hashes are supported in addition to SHA1, which is useful for auditing legacy Windows Auth systems.

- There is a high performance http server which can answer plain/sha1/ntlm hash queries with the count in txt or json. this is performance profiled with Apache Bench

It may be interesting to combine the projects such that my downloader, data pipeline and server tools can also offer a "probabilistic lower disk usage" option alongside the existing ones.  

The 64MB memory during filter build is a bit of a problem for practical applications, given the data is now nearly twice the size as well? You said "We could further partition the problem (by dividing up the set) for lower memory usage". If that's possible, we could reduced that to say 4GB or 8GB (ideally tunable), then we may be able to construct a viable data pipeline with fast setup time and low disk usage for the probabilistic use case. 

Please contact me to discuss ....

**Comment by lemire** [comment]
@oschonrock If you'd like to add a probabilistic-filter feature, I would be happy to work with you on a practical and high-performance approach.

The current project (FastFilter/FilterPassword) is not meant on its own to provide a production-ready solution (though it could work), but rather to illustrate the idea.

**Comment by oschonrock** [comment]
Thanks for prompt response... Great.. 

Today, I have borrowed one idea from your project which is to truncate the sha1 hashes to 64bit. Realistically even with just 64bits the chance of a "hash collision" (and hence a false positive) is still ~10^-10 and therefore not significant. 

So that will (optionally) halve my "row size" to 12 bytes and my full db size to 10.5GB. Since my code was already templated for hash size to support the ntlm hashes, this was quite easy to add, and I am in the testing stage. 

But there is still a 10x disk space improvement possible with the probabilistic approach, at the expense of some non zero false positive rate and a significant memory footprint for the build of the filter. 

It is the latter memory footprint, which I may need some help with. Let me scope the integration, and I will come back to you. 

My intent is that we could get the downloader directly streaming into the filter build (optionally via a topN pipe which can do a streamed `std::partial_sort_copy`). So this will give a lot of flexibility to avoid intermediate materialisations on disk and control both the filter build memory size and the output size. 

Does your code need the hashes in count descending order? Or was that just a convenient way to slice off a topN?

**Comment by lemire** [comment]
The footprint at construction time is fairly easy to work around. Basically, you fragment your filter in N subsets (adjust N accordingly). So if you have a very large input, just set, say, N = 256... then you can build N different filters. At query time, you select the right filter... I could flush it out, but it is not very complicated. To do it well depends on your code base.

If done correctly, you should have high speed and low usage.

I will be happy to help.

**Comment by oschonrock** [comment]
Thanks. I see, doesn't sound too hard.

I have cloned the repo and "streamlined" it somewhat. Mainly to eliminate all the comparative filters and their dependencies. I rewrote the Makefile to reflect these changes while also pushing directories around a little. I am bad at Makefiles, but it seems to work, including the two remaining tests. 

https://github.com/oschonrock/FilterPassword

Quick questions:
==============
1. Is there any reason for me to consider anything except binaryfuse8? 
2. Are there any "space or time / false positive" trade off levers that I need to consider? `arity` ? 
3. given i will be generating multiple filters to reduce the build footprint, is the size of the filter deterministic in advance (based on arity, ...) or can it change during build depending on data? 
4. Are there licensing / methods of inclusion policies that I need to be aware of for the remaining `binaryfusefilter.h`?

**Comment by lemire** [comment]
> Is there any reason for me to consider anything except binaryfuse8?

I think it is a very good choice.

> Are there any "space or time / false positive" trade off levers that I need to consider? arity ?

Yes. At the expense of some added computation, we can move from 3-ary to 4-ary. 

See Binary Fuse Filters: Fast and Smaller Than Xor Filters, Journal of Experimental Algorithmics 27, 2022
https://arxiv.org/pdf/2201.01174

There is probably not sense going to 2-ary or 5-ary. The practical range is 3-ary to 4-ary... but 3-ary is the default I propose. It uses a bit more storage, but it is faster.


> given i will be generating multiple filters to reduce the build footprint, is the size of the filter deterministic in advance (based on arity, ...) or can it change during build depending on data?

It is deterministic: given the number of keys in the set, you can compute exactly the size. The code does the computation, but the topic is also covered in the paper.

> Are there licensing / methods of inclusion policies that I need to be aware of for the remaining binaryfusefilter.h?


There is no patent.

I use Apache:

https://github.com/FastFilter/xor_singleheader/blob/master/LICENSE

That's what you are using as well, so you can just drop the code in your repo.

You will not be sued if that's what you are concerned with.

**Comment by oschonrock** [comment]
Thanks, there wasn't a LICENSE on the FilterPassword repo, so I was just checking before I offend someone. ;-)

I got some build errors when switching to arity=4, but the differences seem small anyway. 

Since posting questions, I have been reading paper, which answered a lot of my questions, inevitably.  Thanks. 

I have just reintroduced the 16bit fuse filter, because it (obviously) has a much reduced false positive rate for twice the storage size, and an end user may want to make that trade-off.

**Comment by lemire** [comment]
> Thanks, there wasn't a LICENSE on the FilterPassword repo

That's right... but it is not really a software library. Maybe I should clarify.

The software library is https://github.com/FastFilter/xor_singleheader/

**Comment by oschonrock** [comment]
ok.. that makes more sense, and that has a more up2date and maintained version of `binaryfusefilter.h` with serialisation etc

I will just import that as a lib.. better. 

Because there was a local copy of that file in this repo, it was not clear to me how that related to that lib. The pertinent parts of this repo do not need that lib in fact.

**Comment by lemire** [comment]
So I am going to close this issue here. If you need my help, just get in touch with me, or open an issue in the library's repo.

**Comment by oschonrock** [comment]
That's good., thanks. 

My confusion arose, because the note you have now added to the  `README.md` of this repo was not there yet, and because the code does **not** in fact depend on https://github.com/FastFilter/xor_singleheader/ but some local copy of an older version of that lib.  

Thanks for your time. The note certainly helps. 

In order to prevent future confusion for others, I am going to re-fork this repo,  make it actually depend upon the up2date lib (via a git submodule as for the other lib [fastfilter_cpp @ 0e85974](https://github.com/FastFilter/fastfilter_cpp/tree/0e859745bf2b08b07dcf5845a2bab23c0245c39b) ), solve any problems  and then offer that as a pull request. 

I hope that's helpful..
